In [1]:
# 사전 준비
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import warnings
plt.style.use('seaborn')
sns.set(font_scale=2.5)

warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
import matplotlib
from matplotlib import font_manager, rc
import platform

if platform.system() == 'Windows':
# 윈도우인 경우
    font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
    rc('font', family=font_name)
else:    
# Mac 인 경우
    rc('font', family='AppleGothic')
    
matplotlib.rcParams['axes.unicode_minus'] = False   


In [3]:
sample = pd.read_csv('../input/final.csv')

print("sample.shape:", sample.shape)

# 초기 샘플 데이터
sample

sample.shape: (72250, 13)


사고내용  도로형태 대분류  기상상태  차량년식  가해자성별     가해자나이  요일  가해차종  노면상태  보행자이동  \
6          3       0.0     1   8.0    2.0  3.332205   5   3.0   1.0    0.0   
8          3       0.0     1   1.0    1.0  3.218876   5   9.0   1.0    2.0   
14         3       0.0     1   1.0    2.0  3.178054   4   9.0   1.0    0.0   
25         3       0.0     1   8.0    2.0  3.891820   7   9.0   1.0    0.0   
26         3       0.0     1   7.0    2.0  3.871201   5   9.0   1.0    3.0   
...      ...       ...   ...   ...    ...       ...  ..   ...   ...    ...   
285297     3       0.0     1  12.0    2.0  3.931826   3   9.0   2.0    1.0   
285307     3       0.0     1  11.0    2.0  3.218876   4   9.0   2.0    0.0   
285312     3       0.0     2   7.0    2.0  4.330733   7   9.0   2.0    0.0   
285313     3       0.0     2   4.0    1.0  3.044522   7   9.0   2.0    0.0   
285314     3       0.0     2   4.0    1.0  3.044522   7   9.0   2.0    0.0   

        빛 세기  사고 위치  사고 조절  
6          7    2.0    2.0  
8          1    1.0    2.0  
14         1    8.0    4.0  
25         1    8.0    4.0  
26         1    8.0    4.0  
...      ...    ...    ...  
285297     4    1.0    4.0  
285307     1    8.0    4.0  
285312     1    1.0    4.0  
285313     1    7.0    4.0  
285314     1    7.0    4.0  

[72250 rows x 13 columns]

In [4]:
from imblearn.combine import *
from imblearn.over_sampling import *

In [5]:
sample["기상상태"] = sample["기상상태"].astype('float')
sample["요일"] = sample["요일"].astype('float')
sample["빛 세기"] = sample["빛 세기"].astype('float')
sample

사고내용  도로형태 대분류  기상상태  차량년식  가해자성별     가해자나이   요일  가해차종  노면상태  보행자이동  \
6          3       0.0   1.0   8.0    2.0  3.332205  5.0   3.0   1.0    0.0   
8          3       0.0   1.0   1.0    1.0  3.218876  5.0   9.0   1.0    2.0   
14         3       0.0   1.0   1.0    2.0  3.178054  4.0   9.0   1.0    0.0   
25         3       0.0   1.0   8.0    2.0  3.891820  7.0   9.0   1.0    0.0   
26         3       0.0   1.0   7.0    2.0  3.871201  5.0   9.0   1.0    3.0   
...      ...       ...   ...   ...    ...       ...  ...   ...   ...    ...   
285297     3       0.0   1.0  12.0    2.0  3.931826  3.0   9.0   2.0    1.0   
285307     3       0.0   1.0  11.0    2.0  3.218876  4.0   9.0   2.0    0.0   
285312     3       0.0   2.0   7.0    2.0  4.330733  7.0   9.0   2.0    0.0   
285313     3       0.0   2.0   4.0    1.0  3.044522  7.0   9.0   2.0    0.0   
285314     3       0.0   2.0   4.0    1.0  3.044522  7.0   9.0   2.0    0.0   

        빛 세기  사고 위치  사고 조절  
6        7.0    2.0    2.0  
8        1.0    1.0    2.0  
14       1.0    8.0    4.0  
25       1.0    8.0    4.0  
26       1.0    8.0    4.0  
...      ...    ...    ...  
285297   4.0    1.0    4.0  
285307   1.0    8.0    4.0  
285312   1.0    1.0    4.0  
285313   1.0    7.0    4.0  
285314   1.0    7.0    4.0  

[72250 rows x 13 columns]

In [6]:
sample = sample.iloc[np.random.permutation(len(sample))]

y = sample.loc[:, sample.columns == '사고내용']
x = sample.loc[:, sample.columns != '사고내용']


from sklearn.preprocessing import MinMaxScaler
minMaxScaler = MinMaxScaler()
print(minMaxScaler.fit(x))
x = minMaxScaler.transform(x)
x

MinMaxScaler()


array([[0.        , 0.        , 0.04807692, ..., 0.        , 0.125     ,
        1.        ],
       [0.        , 0.5       , 0.        , ..., 0.5       , 0.75      ,
        1.        ],
       [0.        , 0.        , 0.125     , ..., 0.        , 0.125     ,
        1.        ],
       ...,
       [0.        , 0.        , 0.05769231, ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.09615385, ..., 0.5       , 0.125     ,
        1.        ],
       [0.        , 0.        , 0.09615385, ..., 0.        , 0.75      ,
        1.        ]])

In [9]:
x = pd.DataFrame(data = x,columns = sample.columns[1:])
x

도로형태 대분류  기상상태      차량년식  가해자성별     가해자나이        요일      가해차종  노면상태  \
0           0.0   0.0  0.048077    0.0  0.805988  1.000000  0.072917  0.00   
1           0.0   0.5  0.000000    0.0  0.884617  1.000000  0.072917  0.25   
2           0.0   0.0  0.125000    0.5  0.812214  0.166667  0.072917  0.00   
3           0.0   0.0  0.000000    0.5  0.496309  1.000000  0.072917  0.00   
4           0.0   0.0  0.125000    0.0  0.481072  0.666667  0.072917  0.00   
...         ...   ...       ...    ...       ...       ...       ...   ...   
72245       0.0   0.0  0.076923    0.5  0.786631  0.333333  0.072917  0.00   
72246       0.0   0.0  0.076923    0.0  0.766168  0.166667  0.072917  0.00   
72247       0.0   0.0  0.057692    0.5  0.641470  0.833333  0.072917  0.00   
72248       0.0   0.0  0.096154    0.5  0.576197  1.000000  0.072917  0.00   
72249       0.0   0.0  0.096154    0.5  0.744464  0.333333  0.072917  0.00   

          보행자이동  빛 세기  사고 위치     사고 조절  
0      0.000000   0.0  0.125  1.000000  
1      0.000000   0.5  0.750  1.000000  
2      0.000000   0.0  0.125  1.000000  
3      0.000000   1.0  0.125  1.000000  
4      0.000000   0.0  1.000  1.000000  
...         ...   ...    ...       ...  
72245  0.000000   0.5  1.000  1.000000  
72246  0.111111   0.0  0.250  0.333333  
72247  0.111111   0.0  1.000  1.000000  
72248  0.000000   0.5  0.125  1.000000  
72249  0.000000   0.0  0.750  1.000000  

[72250 rows x 12 columns]

In [10]:
x_samp , y_samp = ADASYN(random_state = 20000).fit_sample(x,y)
#x_samp2, y_samp2 = SMOTETomek(random_state = 4).fit_sample(x,y)
resample = pd.concat([y_samp,x_samp],axis = 1)


In [11]:
resample.to_csv('../input/final1.csv', encoding='utf-8-sig',index_label=False)

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_samp, y_samp, test_size=0.2,random_state = 1)
#x_train, x_test, y_train, y_test = train_test_split(x_samp2, y_samp2, test_size=0.2)

from sklearn.neighbors import KNeighborsClassifier

#knn = KNeighborsClassifier()
#knn.fit(x_train,y_train)
#pred_knn = knn.predict(x_test)
#val_knn = (pred_knn == y_test["사고내용"]).mean()
#val_knn


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,pred_knn,target_names=['class 0','class 1','class 2']))
cm = confusion_matrix(y_test,pred_knn)
print('Confusion matrix: \n',cm)

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
#tree = DecisionTreeClassifier()
#model2 = BaggingClassifier()
#model2.fit(x_train,y_train)
#tree.fit(x_train,y_train)

#pred = tree.predict(x_test)
#pred_m2 = model2.predict(x_test)
#val = (pred == y_test["사고내용"]).mean()
#val_m2 = (pred_m2 == y_test["사고내용"]).mean()
#print(val , val_m2)

In [14]:
model = RandomForestClassifier()

model.fit(x_train,y_train)

pred_m1 = model.predict(x_test)

val_m1 = (pred_m1 == y_test["사고내용"]).mean()

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,pred_m1,target_names=['class 0','class 1','class 2']))
cm = confusion_matrix(y_test,pred_m1)
print('Confusion matrix: \n',cm)
x_train

              precision    recall  f1-score   support

     class 0       0.98      0.99      0.99     12469
     class 1       0.92      0.90      0.91     12418
     class 2       0.91      0.92      0.91     12522

    accuracy                           0.94     37409
   macro avg       0.94      0.94      0.94     37409
weighted avg       0.94      0.94      0.94     37409

Confusion matrix: 
 [[12363    32    74]
 [  164 11137  1117]
 [   69   929 11524]]


도로형태 대분류      기상상태      차량년식  가해자성별     가해자나이        요일      가해차종  \
53356        0.0  0.000000  0.057692    0.0  0.599302  0.000000  0.062500   
92013        0.0  0.064542  0.086538    0.0  0.488442  0.500000  0.042688   
102598       0.0  0.000000  0.120755    0.0  0.862495  0.666667  0.031250   
35862        0.0  0.000000  0.125000    0.5  0.551497  0.666667  0.072917   
79888        0.0  0.375000  0.076923    0.0  0.868092  0.205174  0.080927   
...          ...       ...       ...    ...       ...       ...       ...   
73349        0.0  0.000000  0.062722    0.0  0.661735  0.833333  0.124656   
109259       0.0  0.000000  0.121900    0.0  0.744068  0.833333  0.072917   
50057        0.0  0.125000  0.096154    0.5  0.641470  0.500000  0.072917   
5192         0.0  0.000000  0.076923    0.5  0.931792  0.333333  0.072917   
128037       0.0  0.000000  0.095165    0.0  0.620440  1.000000  0.072917   

            노면상태     보행자이동      빛 세기     사고 위치     사고 조절  
53356   0.000000  0.000000  0.500000  0.625000  1.000000  
92013   0.129084  0.000000  0.500000  0.185458  1.000000  
102598  0.000000  0.000000  0.000000  1.000000  1.000000  
35862   0.000000  0.000000  0.000000  0.500000  1.000000  
79888   0.000000  0.000000  0.000000  1.000000  1.000000  
...          ...       ...       ...       ...       ...  
73349   0.124175  0.000000  0.833333  1.000000  1.000000  
109259  0.250000  0.258043  0.500000  0.125000  1.000000  
50057   0.250000  0.000000  0.000000  0.125000  0.666667  
5192    0.000000  0.000000  0.000000  0.125000  1.000000  
128037  0.000000  1.000000  0.500000  0.385709  1.000000  

[149633 rows x 12 columns]